import { useEffect, useState } from "react";
import { attachmentDownloadUrl, fetchAttachments, fetchTicket, removeAttachment, uploadAttachment, type Attachment, type DevelopmentRequester, type TicketDetail as TicketDetailData } from "./api";

type State = "loading" | "ready" | "error";
const date = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value));

export default function TicketDetail({ ticketId, requester, onBack }: { ticketId: number; requester: DevelopmentRequester; onBack: () => void }) {
  const [state, setState] = useState<State>("loading");
  const [ticket, setTicket] = useState<TicketDetailData | null>(null);
  const [error, setError] = useState("");
  const [attachments, setAttachments] = useState<Attachment[]>([]);
  const [file, setFile] = useState<File | null>(null);
  const [removalReason, setRemovalReason] = useState("");
  const [attachmentError, setAttachmentError] = useState("");
  async function load() { setState("loading"); setError(""); try { const [loadedTicket, loadedAttachments] = await Promise.all([fetchTicket(ticketId, requester.id), fetchAttachments(ticketId, requester.id)]); setTicket(loadedTicket); setAttachments(loadedAttachments); setState("ready"); } catch (reason) { setTicket(null); setError(reason instanceof Error ? reason.message : "Unable to load this ticket."); setState("error"); } }
  useEffect(() => { void load(); }, [ticketId, requester.id]);
  async function upload() { if (!file) return; setAttachmentError(""); try { await uploadAttachment(ticketId, requester.id, file); setFile(null); await load(); } catch (reason) { setAttachmentError(reason instanceof Error ? reason.message : "Unable to upload attachment."); } }
  async function remove(id: number) { if (removalReason.trim().length < 5) { setAttachmentError("Removal reason must be between 5 and 500 characters."); return; } setAttachmentError(""); try { await removeAttachment(id, requester.id, removalReason.trim()); setRemovalReason(""); await load(); } catch (reason) { setAttachmentError(reason instanceof Error ? reason.message : "Unable to remove attachment."); } }
  return <section className="card shadow-sm border-0" aria-labelledby="ticket-detail-heading"><div className="card-body p-4 p-md-5"><button className="btn btn-toktickit-outline mb-4" onClick={onBack}>Back to My Tickets</button><h1 id="ticket-detail-heading" className="h3 mb-4">Ticket Detail</h1>{state === "loading" && <p role="status">Loading ticket...</p>}{state === "error" && <div className="alert alert-danger" role="alert"><strong>Ticket unavailable</strong><div>{error}</div><button className="btn btn-outline-danger mt-3" onClick={() => void load()}>Try again</button></div>}{state === "ready" && ticket && <><div className="row g-3"><Field label="Ticket Number" value={ticket.ticketNumber} /><Field label="Ticket Date" value={date(ticket.createdAt)} /><Field label="Requester" value={ticket.requester.name} /><Field label="Category" value={ticket.category.name} /><Field label="Related System" value={ticket.relatedSystem.name} /><Field label="Summary" value={ticket.summary} /><Field label="Requested Priority" value={ticket.requestedPriority} /><Field label="Current Status" value={ticket.currentStatus} /><Field label="Description" value={ticket.description} wide /></div><div className="mb-3"><label className="form-label" htmlFor="attachment-removal-reason">Removal reason</label><input id="attachment-removal-reason" className="form-control" value={removalReason} onChange={(event) => setRemovalReason(event.target.value)} /></div><section className="mt-5" aria-labelledby="attachments-heading"><h2 id="attachments-heading" className="h5">Attachments</h2><div className="d-flex gap-2 mb-3"><input aria-label="Attachment file" className="form-control" type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><button className="btn btn-toktickit-primary" disabled={!file} onClick={() => void upload()}>Upload</button></div>{attachmentError && <div className="alert alert-danger" role="alert">{attachmentError}</div>}{state === "ready" && (attachments.length ? <ul className="list-group">{attachments.map((attachment) => <li className="list-group-item" key={attachment.id}><strong>{attachment.originalFilename}</strong> {attachment.removedAt ? <span className="badge text-bg-secondary ms-2">Removed</span> : <><a className="btn btn-sm btn-toktickit-outline ms-2" href={attachmentDownloadUrl(attachment.id, requester.id)}>Download</a><button className="btn btn-sm btn-outline-danger ms-2" onClick={() => void remove(attachment.id)}>Remove</button></>}</li>)}</ul> : <p className="text-secondary mb-0">No attachments yet.</p>)}</section></>}</div></section>;
}

function Field({ label, value, wide = false }: { label: string; value: string; wide?: boolean }) { return <div className={wide ? "col-12" : "col-md-6"}><div className="form-label fw-semibold">{label}</div><div className="form-control toktickit-readonly">{value}</div></div>; }
