import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(new URL("../../client/package.json", import.meta.url));
const { chromium } = require("playwright");
const root = fileURLToPath(new URL("./", import.meta.url));
const repository = "https://github.com/SupeemAFK/TokTickIT-Individual-Sprints";
const screenshot = (name, label) => {
  const file = root + "screenshots/" + name;
  const data = readFileSync(file).toString("base64");
  return `<figure><img src="data:image/png;base64,${data}"><figcaption>${label}</figcaption></figure>`;
};
const html = `<!doctype html><html><head><meta charset="utf-8"><style>
@page{size:A4;margin:18mm 14mm 14mm}*{box-sizing:border-box}body{font:10.5pt Arial,sans-serif;color:#18261f;line-height:1.4}a{color:#075f3f}h1{font-size:25pt;color:#0d6a47;margin:0 0 8px}h2{font-size:16pt;color:#0d6a47;border-bottom:2px solid #b9dcca;padding-bottom:4px;margin:0 0 10px;break-after:avoid-page}section{break-before:page}section:first-of-type{break-before:auto}.meta,.ok,.notice{padding:12px;margin:12px 0}.meta{background:#eef8f2;border-left:5px solid #0d6a47}.ok{background:#eaf7ef;border-left:4px solid #14804a}.notice{background:#fff8df;border-left:4px solid #a77500}figure{margin:12px 0 16px;break-inside:avoid}img{display:block;max-width:100%;max-height:205mm;margin:auto;border:1px solid #bdc8c0}figcaption{font-size:8.5pt;color:#4d5c52;margin-top:4px;text-align:center}li{margin:4px 0}.cover{min-height:245mm;display:flex;flex-direction:column;justify-content:center;break-after:page}.small{font-size:9pt}.footer{font-size:8pt;color:#627067}
</style></head><body>
<div class="cover"><h1>TokTickIT — Lab 3 Submission Report</h1><p>Release evidence for authenticated requester, IT staff, administrator, testing, review, and delivery work.</p><div class="meta"><strong>Repository:</strong> <a href="${repository}">TokTickIT-Individual-Sprints</a><br><strong>Pull request:</strong> <a href="${repository}/pull/43">PR #43</a> <code>lab3-staging → main</code><br><strong>Implementation commit:</strong> <a href="${repository}/commit/f4be28a">f4be28a</a><br><strong>Evidence commit:</strong> generated with this report</div><div class="notice"><strong>Evidence boundary.</strong> Browser captures are deterministic Playwright API-fixture captures. They document the submitted UI states and are not presented as live production records. API authorization and workflow claims are backed by the server test suite.</div><div class="ok"><strong>Verification:</strong> server 14 files / 45 tests, client 8 files / 20 tests, 2 Playwright tests, and both production builds passed.</div></div>
<section><h2>Scope completed</h2><ul><li>Bearer-session authentication, password-change gate, logout, and safe inactive-user handling.</li><li>Requester ticket list, validated atomic creation, detail, attachments, public comments, and appears-resolved workflow.</li><li>IT staff queue/detail, search and status filtering, atomic claim, workflow transitions, public comments, and internal notes.</li><li>Administrator user listing, account creation, role editing, deactivation guards, and duplicate-email handling.</li><li>API, component, authenticated E2E, responsive, documentation, and GitHub review evidence.</li></ul><h2>Verification commands</h2><p><code>cd server &amp;&amp; npm test &amp;&amp; npm run build</code><br><code>cd client &amp;&amp; npm test &amp;&amp; npm run build</code><br><code>cd client &amp;&amp; npm run test:e2e</code></p><p class="footer">See <code>artifacts/lab-03/EVIDENCE.md</code> and <code>docs/lab-03/tests.md</code> for the traceability details.</p></section>
<section><h2>Authenticated requester and responsive captures</h2>${screenshot("requester-detail.png", "Requester ticket detail with attachment metadata and public comment.")}${screenshot("requester-1440.png", "Requester screen at 1440px desktop width.")}${screenshot("requester-768.png", "Requester screen at 768px tablet width.")}${screenshot("requester-375.png", "Requester screen at 375px mobile width.")}<p class="small">These captures were generated by <code>client/e2e/lab-03/authenticated-requester.spec.ts</code> after the test assertions passed.</p></section>
<section><h2>Review and delivery record</h2><p><a href="${repository}/pull/43#issuecomment-5734114470">Author response to requested changes</a> records the implementation and verification results. The collaborator review remains pending re-review; this report does not claim approval or merge.</p><p>The release evidence files include the AI-use disclosure, review trail, test traceability, screenshots, and this PDF. The source remains on <code>lab3-staging</code> until the collaborator completes review and merges PR #43.</p></section>
</body></html>`;

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setContent(html, { waitUntil: "load" });
await page.pdf({
  path: root + "TokTickIT-Lab-3-Submission-Report.pdf",
  format: "A4",
  printBackground: true,
  displayHeaderFooter: true,
  headerTemplate: `<div style="width:100%;font:8pt Arial,sans-serif;color:#245c42;text-align:right;padding:4mm 14mm 0 0;line-height:1.3"><strong>TokTickIT Lab 3</strong><br>PR #43</div>`,
  footerTemplate: `<div style="width:100%;font:8pt Arial,sans-serif;color:#627067;text-align:center">Release evidence — collaborator re-review pending</div>`,
  margin: { top: "22mm", bottom: "16mm", left: "12mm", right: "12mm" },
});
await browser.close();
