import { randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import type { Express, NextFunction, Request, Response } from "express";
import { UserRole } from "@prisma/client";
import { getPrisma } from "./prisma.js";
import { formatTicketNumber } from "./ticket-number.js";

type Principal = { id: number; role: UserRole; legacyRequesterId: number | null; mustChangePassword: boolean };
const sessions = new Map<string, { userId: number; expiresAt: number }>();
const ROLES = new Set(Object.values(UserRole));
const statuses = new Set(["NEW", "OPEN", "IN_PROGRESS", "WAITING_FOR_REQUESTER", "RESOLVED", "CLOSED", "REOPENED", "CANCELLED"]);
const priorities = new Set(["LOW", "MEDIUM", "HIGH"]);
const allowedTransitions: Record<string, string[]> = { NEW:["OPEN","IN_PROGRESS","CANCELLED"], OPEN:["IN_PROGRESS","WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"], IN_PROGRESS:["WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"], WAITING_FOR_REQUESTER:["IN_PROGRESS","RESOLVED","CANCELLED"], RESOLVED:["CLOSED","REOPENED"], CLOSED:["REOPENED"], REOPENED:["IN_PROGRESS","WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"], CANCELLED:[] };
const hash = (password: string) => { const salt=randomBytes(16).toString("hex"); return `${salt}:${scryptSync(password,salt,64).toString("hex")}`; };
const valid = (password:string, encoded:string) => { const [salt,value]=encoded.split(":"); const candidate=scryptSync(password,salt,64).toString("hex"); return timingSafeEqual(Buffer.from(value,"hex"),Buffer.from(candidate,"hex")); };
const safeUser = (u: any) => ({ id:u.id,name:u.name,email:u.email,role:u.role,isActive:u.isActive,mustChangePassword:u.mustChangePassword,legacyRequesterId:u.legacyRequesterId });
function err(res:Response,status:number,error:string) { return res.status(status).json({error}); }
async function principal(req:Request):Promise<Principal|null> { const token=req.header("authorization")?.replace(/^Bearer\s+/i,""); const session=token && sessions.get(token); if (!session || session.expiresAt<Date.now()) return null; const u=await getPrisma().user.findUnique({where:{id:session.userId}}); if(!u||!u.isActive) return null; return {id:u.id,role:u.role,legacyRequesterId:u.legacyRequesterId,mustChangePassword:u.mustChangePassword}; }
function protect(roles?:UserRole[]) { return async (req:Request,res:Response,next:NextFunction) => { const user=await principal(req); if(!user) return err(res,401,"Authentication is required."); if(user.mustChangePassword && req.path!=="/api/auth/change-password") return err(res,403,"Password change is required."); if(roles && !roles.includes(user.role)) return err(res,403,"You are not permitted to perform this action."); (req as any).user=user; next(); }; }
function text(v:any,label:string,min=1,max=2000) { if(typeof v!=="string" || v.trim().length<min || v.trim().length>max) throw new Error(`${label} must be between ${min} and ${max} characters.`); return v.trim(); }
export async function authenticatedRequesterId(req:Request):Promise<number|null> { const u=await principal(req); return u?.role===UserRole.REQUESTER && !u.mustChangePassword ? u.legacyRequesterId : null; }
export function registerLab3(app:Express) {
 app.post("/api/auth/login",async(req,res)=>{ try { const email=text(req.body?.email,"Email",3,320).toLowerCase(), password=text(req.body?.password,"Password",8,200); const u=await getPrisma().user.findUnique({where:{email}}); if(!u||!u.isActive||!valid(password,u.passwordHash)) return err(res,401,"Invalid email or password."); const token=randomBytes(32).toString("hex"); sessions.set(token,{userId:u.id,expiresAt:Date.now()+8*60*60*1000}); res.json({token,user:safeUser(u),mustChangePassword:u.mustChangePassword}); } catch(e) { err(res,400,e instanceof Error?e.message:"Invalid login."); }});
 app.post("/api/auth/logout",protect(),(req,res)=>{ const token=req.header("authorization")!.replace(/^Bearer\s+/i,""); sessions.delete(token); res.status(204).end(); });
 app.get("/api/auth/me",protect(),async(req,res)=>{ const u=await getPrisma().user.findUnique({where:{id:(req as any).user.id}}); res.json({user:safeUser(u)}); });
 app.post("/api/auth/change-password",protect(),async(req,res)=>{ try { const password=text(req.body?.password,"Password",12,200); if(!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/[0-9]/.test(password)) return err(res,400,"Password must include upper-case, lower-case, and number characters."); await getPrisma().user.update({where:{id:(req as any).user.id},data:{passwordHash:hash(password),mustChangePassword:false}}); res.status(204).end(); }catch(e){err(res,400,e instanceof Error?e.message:"Invalid password.");} });
 app.get("/api/staff/tickets",protect([UserRole.IT_STAFF,UserRole.ADMINISTRATOR]),async(req,res)=>{ const q=typeof req.query.search==="string"?req.query.search.trim():""; const page=Math.max(1,Number(req.query.page)||1), pageSize=[10,20,50].includes(Number(req.query.pageSize))?Number(req.query.pageSize):10; const where:any={...(q?{OR:[{ticketNumber:{contains:q,mode:"insensitive"}},{summary:{contains:q,mode:"insensitive"}}]}:{}),...(typeof req.query.status==="string"&&statuses.has(req.query.status)?{currentStatus:req.query.status}:{}),...(typeof req.query.assigned === "string" ? (req.query.assigned === "unassigned" ? { ownerUserId: null } : (Number.isSafeInteger(Number(req.query.assigned)) && Number(req.query.assigned) > 0 ? { ownerUserId: Number(req.query.assigned) } : {})) : {})}; const [items,totalItems]=await Promise.all([getPrisma().ticket.findMany({where,skip:(page-1)*pageSize,take:pageSize,orderBy:{updatedAt:"desc"},include:{requester:true,owner:{select:{id:true,name:true,email:true}},category:true,relatedSystem:true}}),getPrisma().ticket.count({where})]); res.json({items,pagination:{page,pageSize,totalItems,totalPages:Math.ceil(totalItems/pageSize)}}); });
 app.get("/api/staff/tickets/:id",protect([UserRole.IT_STAFF,UserRole.ADMINISTRATOR]),async(req,res)=>{ const t=await getPrisma().ticket.findUnique({where:{id:Number(req.params.id)},include:{requester:true,owner:{select:{id:true,name:true}},category:true,relatedSystem:true,attachments:true,publicComments:{include:{author:{select:{id:true,name:true,role:true}}}},internalNotes:{include:{author:{select:{id:true,name:true,role:true}}}}}}); if(!t)return err(res,404,"Ticket not found.");res.json(t); });
 app.patch("/api/staff/tickets/:id",protect([UserRole.IT_STAFF,UserRole.ADMINISTRATOR]),async(req,res)=>{ const id=Number(req.params.id),body=req.body??{},t=await getPrisma().ticket.findUnique({where:{id}}); if(!t)return err(res,404,"Ticket not found."); const data:any={}; if(body.claim){const claimed=await getPrisma().ticket.updateMany({where:{id,ownerUserId:null},data:{ownerUserId:(req as any).user.id}});if(!claimed.count)return err(res,409,"Ticket is already assigned.");} if(body.ownerUserId!==undefined) { const o=await getPrisma().user.findFirst({where:{id:Number(body.ownerUserId),isActive:true,role:{in:[UserRole.IT_STAFF,UserRole.ADMINISTRATOR]}}}); if(!o)return err(res,400,"Owner must be an active staff user.");data.ownerUserId=o.id;} if(body.itPriority){if(!priorities.has(body.itPriority))return err(res,400,"Invalid IT Priority.");data.itPriority=body.itPriority;} if(body.currentStatus){if(!statuses.has(body.currentStatus)||!allowedTransitions[t.currentStatus].includes(body.currentStatus))return err(res,409,"Status transition is not permitted.");data.currentStatus=body.currentStatus;} res.json(await getPrisma().ticket.update({where:{id},data})); });
 app.post("/api/staff/tickets/:id/comments",protect([UserRole.IT_STAFF,UserRole.ADMINISTRATOR]),async(req,res)=>{try{res.status(201).json(await getPrisma().publicComment.create({data:{ticketId:Number(req.params.id),authorId:(req as any).user.id,content:text(req.body?.content,"Comment",1,2000)},include:{author:{select:{id:true,name:true,role:true}}}}));}catch(e){err(res,400,e instanceof Error?e.message:"Invalid comment.");}});
 app.post("/api/staff/tickets/:id/notes",protect([UserRole.IT_STAFF,UserRole.ADMINISTRATOR]),async(req,res)=>{try{res.status(201).json(await getPrisma().internalNote.create({data:{ticketId:Number(req.params.id),authorId:(req as any).user.id,content:text(req.body?.content,"Note",1,2000)},include:{author:{select:{id:true,name:true,role:true}}}}));}catch(e){err(res,400,e instanceof Error?e.message:"Invalid note.");}});
 app.get("/api/admin/users",protect([UserRole.ADMINISTRATOR]),async(req,res)=>{const q=typeof req.query.search==="string"?req.query.search.trim():""; const role=typeof req.query.role==="string"&&ROLES.has(req.query.role as UserRole)?req.query.role as UserRole:undefined;res.json((await getPrisma().user.findMany({where:{...(role?{role}:{}),...(q?{OR:[{name:{contains:q,mode:"insensitive"}},{email:{contains:q,mode:"insensitive"}}]}:{})},orderBy:{name:"asc"}})).map(safeUser));});
 app.post("/api/admin/users",protect([UserRole.ADMINISTRATOR]),async(req,res)=>{try{const b=req.body??{},role=b.role as UserRole;if(!ROLES.has(role))return err(res,400,"Invalid role.");const u=await getPrisma().user.create({data:{name:text(b.name,"Name",2,120),email:text(b.email,"Email",3,320).toLowerCase(),role,isActive:b.isActive!==false,passwordHash:hash(text(b.initialPassword,"Initial password",12,200)),mustChangePassword:true}});res.status(201).json(safeUser(u));}catch(e:any){err(res,e?.code==="P2002"?409:400,e?.code==="P2002"?"Email is already in use.":e.message||"Invalid user.");}});
 app.patch("/api/admin/users/:id",protect([UserRole.ADMINISTRATOR]),async(req,res)=>{try{const id=Number(req.params.id),b=req.body??{},me=(req as any).user;const target=await getPrisma().user.findUnique({where:{id}});if(!target)return err(res,404,"User not found.");const nextRole=(b.role??target.role) as UserRole,nextActive=b.isActive??target.isActive;if(!ROLES.has(nextRole))return err(res,400,"Invalid role.");if(id===me.id&&!nextActive)return err(res,409,"You cannot deactivate your own account.");if(target.role===UserRole.ADMINISTRATOR&&(nextRole!==UserRole.ADMINISTRATOR||!nextActive)){const count=await getPrisma().user.count({where:{role:UserRole.ADMINISTRATOR,isActive:true}});if(count<=1)return err(res,409,"At least one active Administrator is required.");}const u=await getPrisma().user.update({where:{id},data:{...(b.name?{name:text(b.name,"Name",2,120)}:{}),...(b.email?{email:text(b.email,"Email",3,320).toLowerCase()}:{}),role:nextRole,isActive:nextActive,...(b.initialPassword?{passwordHash:hash(text(b.initialPassword,"Initial password",12,200)),mustChangePassword:true}:{})}});res.json(safeUser(u));}catch(e:any){err(res,e?.code==="P2002"?409:400,e?.code==="P2002"?"Email is already in use.":e.message||"Invalid user.");}});
 app.get("/api/requester/tickets",protect([UserRole.REQUESTER]),async(req,res)=>{const u=(req as any).user; if(!u.legacyRequesterId)return err(res,403,"Requester account is not linked to a requester record.");const items=await getPrisma().ticket.findMany({where:{requesterId:u.legacyRequesterId},include:{category:true,relatedSystem:true},orderBy:{updatedAt:"desc"}});res.json({items});});
 app.get("/api/requester/tickets/:id",protect([UserRole.REQUESTER]),async(req,res)=>{const u=(req as any).user; if(!u.legacyRequesterId)return err(res,403,"Requester account is not linked to a requester record.");const ticket=await getPrisma().ticket.findFirst({where:{id:Number(req.params.id),requesterId:u.legacyRequesterId},include:{category:true,relatedSystem:true,attachments:{select:{id:true,originalFilename:true,mimeType:true,byteSize:true,createdAt:true,removedAt:true,removalReason:true},orderBy:{createdAt:"asc"}},publicComments:{include:{author:{select:{id:true,name:true,role:true}}},orderBy:{createdAt:"asc"}}}});if(!ticket)return err(res,404,"Ticket not found.");res.json(ticket);});
 app.post("/api/requester/tickets",protect([UserRole.REQUESTER]),async(req,res)=>{try{const u=(req as any).user;if(!u.legacyRequesterId)return err(res,403,"Requester account is not linked to a requester record.");const b=req.body??{};const categoryId=Number(b.categoryId),relatedSystemId=Number(b.relatedSystemId),summary=text(b.summary,"Summary",5,160),description=text(b.description,"Description",10,4000);if(!Number.isSafeInteger(categoryId)||categoryId<1||!Number.isSafeInteger(relatedSystemId)||relatedSystemId<1)return err(res,400,"Category and related system are required.");if(!priorities.has(b.requestedPriority))return err(res,400,"Invalid requested priority.");const ticket=await getPrisma().$transaction(async(tx:any)=>{const [category,relatedSystem]=await Promise.all([tx.category.findFirst({where:{id:categoryId,isActive:true},select:{id:true}}),tx.relatedSystem.findFirst({where:{id:relatedSystemId,isActive:true},select:{id:true}})]);if(!category||!relatedSystem)throw new Error("Category or related system is unavailable.");const draft=await tx.ticket.create({data:{ticketNumber:`PENDING-${randomBytes(12).toString("hex")}`,requesterId:u.legacyRequesterId,categoryId,relatedSystemId,summary,description,requestedPriority:b.requestedPriority,itPriority:b.requestedPriority,currentStatus:"NEW"},select:{id:true,createdAt:true}});return tx.ticket.update({where:{id:draft.id},data:{ticketNumber:formatTicketNumber(draft.id,draft.createdAt)},include:{category:true,relatedSystem:true}});});res.status(201).json(ticket);}catch(e){err(res,400,e instanceof Error?e.message:"Unable to create ticket.");}});
 app.post("/api/requester/tickets/:id/comments",protect([UserRole.REQUESTER]),async(req,res)=>{try{const u=(req as any).user;const ticket=await getPrisma().ticket.findFirst({where:{id:Number(req.params.id),requesterId:u.legacyRequesterId}});if(!ticket)return err(res,404,"Ticket not found.");res.status(201).json(await getPrisma().publicComment.create({data:{ticketId:ticket.id,authorId:u.id,content:text(req.body?.content,"Comment",1,2000)}}));}catch(e){err(res,400,e instanceof Error?e.message:"Invalid comment.");}});
 app.post("/api/requester/tickets/:id/appears-resolved",protect([UserRole.REQUESTER]),async(req,res)=>{const u=(req as any).user;const ticket=await getPrisma().ticket.findFirst({where:{id:Number(req.params.id),requesterId:u.legacyRequesterId}});if(!ticket)return err(res,404,"Ticket not found.");res.json(await getPrisma().ticket.update({where:{id:ticket.id},data:{requesterReportedResolvedAt:new Date()}}));});
}
